### Project 2018

Choose a real-world phenomenon that can be measured and for which you could collect at least one-hundred data points across at least four different variables


#### My project is related In  2016 to 2017 year how many person got job and came from out side of ireland.

***Year*** ,***Job*** ,***Age***, ***Gender***,***Salary***



In [17]:
#  modules we need:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#same set of numbers will appear every time
np.random.seed(123)
# Creating first variable (Year)
# from 2010 to 2018 generate 100 years
Year = np.random.randint(2016,2018,100)# min year 2016 maxyear 2018-1 size=100
Year


array([2016, 2017, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2016, 2017,
       2017, 2016, 2017, 2016, 2017, 2016, 2017, 2017, 2016, 2016, 2016,
       2017, 2017, 2017, 2016, 2017, 2016, 2016, 2016, 2016, 2017, 2017,
       2017, 2016, 2016, 2017, 2016, 2016, 2017, 2016, 2017, 2016, 2017,
       2017, 2017, 2016, 2016, 2016, 2016, 2017, 2017, 2016, 2016, 2017,
       2016, 2017, 2016, 2016, 2017, 2016, 2017, 2016, 2017, 2016, 2016,
       2016, 2016, 2017, 2016, 2016, 2017, 2017, 2017, 2017, 2016, 2016,
       2016, 2016, 2017, 2017, 2016, 2016, 2016, 2016, 2017, 2016, 2017,
       2017, 2016, 2017, 2017, 2017, 2016, 2017, 2017, 2017, 2016, 2016,
       2016])

In [18]:
# Creating Second variable (job)

#Job=np.random.randint(0, 7, 100)# 0= min ,7 is max and size=100
#Job
# creating a number of  jobtypes 
#same set of numbers will appear every time
np.random.seed(123)
Jobtypes=['Doctors', 'IT Engineer','Scientist','researchYouth','Administrator']
Job=np.random.choice(Jobtypes,100) # size is 100
Job

array(['Scientist', 'Administrator', 'Scientist', 'IT Engineer',
       'researchYouth', 'Scientist', 'researchYouth', 'IT Engineer',
       'IT Engineer', 'Doctors', 'IT Engineer', 'IT Engineer', 'Doctors',
       'Doctors', 'IT Engineer', 'researchYouth', 'Administrator',
       'Doctors', 'Doctors', 'Administrator', 'IT Engineer',
       'researchYouth', 'Scientist', 'Administrator', 'Scientist',
       'Administrator', 'Doctors', 'Doctors', 'IT Engineer',
       'researchYouth', 'Administrator', 'Administrator', 'Administrator',
       'IT Engineer', 'researchYouth', 'Scientist', 'IT Engineer',
       'Administrator', 'Doctors', 'researchYouth', 'Scientist',
       'Doctors', 'researchYouth', 'Scientist', 'Scientist', 'Scientist',
       'Scientist', 'Administrator', 'researchYouth', 'researchYouth',
       'Administrator', 'Administrator', 'researchYouth', 'Scientist',
       'Doctors', 'Administrator', 'researchYouth', 'IT Engineer',
       'researchYouth', 'Scientist', 'IT Engin

In [19]:

# Creating Third variable (Age)
#same set of numbers will appear every time
np.random.seed(123)
Age= np.random.randint(18,51,100)#min age 18 max age 50  and size is 100
Age


array([20, 46, 35, 37, 40, 50, 27, 50, 50, 43, 37, 32, 50, 34, 22, 21, 20,
       38, 20, 38, 25, 46, 39, 48, 45, 30, 21, 23, 18, 29, 28, 40, 31, 36,
       33, 45, 48, 24, 44, 34, 24, 32, 29, 25, 19, 43, 38, 30, 36, 35, 19,
       45, 40, 21, 21, 29, 39, 43, 21, 29, 21, 48, 24, 27, 41, 32, 37, 24,
       30, 45, 35, 28, 19, 34, 23, 40, 33, 43, 18, 47, 19, 37, 22, 48, 25,
       47, 19, 30, 21, 25, 42, 24, 31, 46, 38, 50, 42, 31, 26, 32])

In [20]:
# Creating Fourth variable (Gender)
#same set of numbers will appear every time
np.random.seed(123)
#Generate a uniform random sample from Gender of size 100 with replacement:
Gender = ['Male', 'Female']
Gender = np.random.choice(Gender,100) # size is 100
len(Gender)

100

In [21]:
# Creating Fifth variable (Salary)
#same set of numbers will appear every time
np.random.seed(123)
# Random hours person work in ireland 6 to 20 hours
hours=np.random.randint(6,12,100)
# Random money paid min 10 euro to 20 euro 
money=np.random.randint(10,20,100)
Salary=hours*money
Salary



array([209, 128, 160, 128,  77, 117, 112, 117,  77,  70,  90, 126, 112,
       108, 114,  77,  90, 143, 110,  78,  84, 170, 112,  99, 112, 130,
       104, 170,  96, 198,  96,  98, 126, 170, 100, 100, 133, 198, 162,
       112, 126, 160,  66, 144, 144, 187, 114,  99, 136,  88, 136, 209,
       144, 170,  99, 117, 121, 180, 170, 165,  99,  96,  90, 120, 108,
       133, 117,  96, 176, 119, 152, 110,  78, 126, 130, 136, 133, 133,
       117, 130, 165, 112,  60, 108, 153, 119, 126, 126, 135, 110, 126,
       133,  96, 135,  99, 135, 171,  72,  98, 117])

### Synthesise/simulate a data set

***Adding  all five variable in data frame ***

In [22]:
# using pandas lib to create data frame
import pandas as pd
Df= pd.DataFrame({"Year":Year,"Job":Job,"Age":Age,"Gender":Gender,"Daily Income":Salary})

In [23]:
Df

Age  Daily Income  Gender            Job  Year
0    20           209    Male      Scientist  2016
1    46           128  Female  Administrator  2017
2    35           160    Male      Scientist  2016
3    37           128    Male    IT Engineer  2016
4    40            77    Male  researchYouth  2016
5    50           117    Male      Scientist  2016
6    27           112    Male  researchYouth  2016
7    50           117  Female    IT Engineer  2017
8    50            77  Female    IT Engineer  2017
9    43            70    Male        Doctors  2016
10   37            90  Female    IT Engineer  2017
11   32           126  Female    IT Engineer  2017
12   50           112    Male        Doctors  2016
13   34           108  Female        Doctors  2017
14   22           114    Male    IT Engineer  2016
15   21            77  Female  researchYouth  2017
16   20            90    Male  Administrator  2016
17   38           143  Female        Doctors  2017
18   20           110  Female        Doctors  2017
19   38            78    Male  Administrator  2016
20   25            84    Male    IT Engineer  2016
21   46           170    Male  researchYouth  2016
22   39           112  Female      Scientist  2017
23   48            99  Female  Administrator  2017
24   45           112  Female      Scientist  2017
25   30           130    Male  Administrator  2016
26   21           104  Female        Doctors  2017
27   23           170    Male        Doctors  2016
28   18            96    Male    IT Engineer  2016
29   29           198    Male  researchYouth  2016
..  ...           ...     ...            ...   ...
70   35           152    Male  Administrator  2016
71   28           110  Female    IT Engineer  2017
72   19            78  Female        Doctors  2017
73   34           126  Female        Doctors  2017
74   23           130  Female  researchYouth  2017
75   40           136    Male    IT Engineer  2016
76   33           133    Male  researchYouth  2016
77   43           133    Male  researchYouth  2016
78   18           117    Male  researchYouth  2016
79   47           130  Female    IT Engineer  2017
80   19           165  Female    IT Engineer  2017
81   37           112    Male      Scientist  2016
82   22            60    Male  researchYouth  2016
83   48           108    Male  researchYouth  2016
84   25           153    Male  researchYouth  2016
85   47           119  Female  researchYouth  2017
86   19           126    Male        Doctors  2016
87   30           126  Female    IT Engineer  2017
88   21           135  Female  researchYouth  2017
89   25           110    Male    IT Engineer  2016
90   42           126  Female  Administrator  2017
91   24           133  Female  researchYouth  2017
92   31            96  Female    IT Engineer  2017
93   46           135    Male      Scientist  2016
94   38            99  Female  researchYouth  2017
95   50           135  Female  Administrator  2017
96   42           171  Female  researchYouth  2017
97   31            72    Male    IT Engineer  2016
98   26            98    Male        Doctors  2016
99   32           117    Male        Doctors  2016

[100 rows x 5 columns]

 Checking Number of count for JOB

In [24]:
Df['Job'].value_counts()

researchYouth    26
IT Engineer      23
Administrator    18
Scientist        17
Doctors          16
Name: Job, dtype: int64

Checking Number of count for Male and Female

In [193]:
Df['Gender'].value_counts()

Male      59
Female    41
Name: Gender, dtype: int64

In [194]:
# While describing data set Gender and Job were not appering because its in string form.
#Number each group from 0 to the number of groups - 1.

In [195]:
Df['Gender'] = Df.groupby('Gender').ngroup()
Df['Daily Income'] = Df.groupby('Daily Income').ngroup()

Generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution

In [196]:
Df.describe()

Age  Daily Income      Gender         Year
count  100.000000    100.000000  100.000000   100.000000
mean    32.090000     20.640000    0.590000  2016.490000
std     10.207044     12.250351    0.494311     0.502418
min     18.000000      0.000000    0.000000  2016.000000
25%     22.000000      9.750000    0.000000  2016.000000
50%     33.000000     21.000000    1.000000  2016.000000
75%     40.250000     30.000000    1.000000  2017.000000
max     50.000000     43.000000    1.000000  2017.000000

In [197]:


from faker import Faker
import random
import numpy as np
import pandas as pd
fake = Faker()
fake.random.getstate()
fake.address()
fake.country()
fake.job()
fake.name()
fake.year()
#for i in range(10):
  #j=[fake.name()]
  #(j)
  #print(fake.address())
 # print(fake.country())
  #print(fake.job())
  #print(fake.random.getstate())
  #tt= pd.DataFrame(i)
#t=fake.date_time_between_dates(datetime_start=None, datetime_end=None)
#t



'2003'

In [122]:
df=[fake.name()for i in range (10)]
df1=[fake.country()for i in range (10)]
df2=[fake.year()for i in range (10)]
df3=[fake.job()for i in range (10)]
#tt= pd.DataFrame(np.random.randn(len(NAME)),index=NAME,columns=["FULLNAME"])
#tt= pd.DataFrame([j])
#tt= pd.DataFrame(df,df1,columns=["FULLNAME","FULLNAME1"])


#print(type(df))
df3

['Engineer, energy',
 'Engineer, materials',
 'Rural practice surveyor',
 'Higher education careers adviser',
 'Archivist',
 'Engineering geologist',
 'Forensic scientist',
 'Multimedia programmer',
 'Food technologist',
 'Furniture conservator/restorer']

In [24]:
tt= pd.DataFrame({"job":df3,"Year":df2,"NAMES":df,"COUNTRY":df1})

In [25]:
tt

COUNTRY              NAMES  Year  \
0     Micronesia      Sergio Taylor  1991   
1          India       Victor Lopez  1998   
2        Bolivia      Tiffany Giles  1973   
3           Guam      Diana Goodwin  2003   
4         Turkey        Amber Potts  2014   
5  Faroe Islands         Alexa Yang  1991   
6         Panama     Joshua Hopkins  1970   
7         Guyana        Bryan Black  1997   
8       Barbados  Stephen Smith Jr.  2007   
9       Thailand       Colleen Hays  1998   

                                        job  
0                           Energy engineer  
1                        Facilities manager  
2                               Comptroller  
3  Conservation officer, historic buildings  
4                             Warden/ranger  
5                               Interpreter  
6                Surveyor, building control  
7                       Art gallery manager  
8       Scientist, research (life sciences)  
9                  Customer service manager

In [26]:
ss=tt.sample(3)

In [27]:
ss

COUNTRY           NAMES  Year                         job
7    Guyana     Bryan Black  1997         Art gallery manager
9  Thailand    Colleen Hays  1998    Customer service manager
6    Panama  Joshua Hopkins  1970  Surveyor, building control

### References

https://stackoverflow.com/questions/22639587/random-seed-what-does-it-do

https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
https://docs.python.org/3/library/statistics.html