### Project 2018

Choose a real-world phenomenon that can be measured and for which you could collect at least one-hundred data points across at least four different variables


#### My project is related In  2016 to 2017 year how many person got job and came from out side of ireland.

***Year*** ,***Job*** ,***Age***, ***Gender***,***Salary***



In [176]:
#  modules we need:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Creating first variable (Year)
# from 2010 to 2018 generate 100 years
Year = np.random.randint(2016,2018,100)# min year 2016 maxyear 2018-1 size=100
Year


array([2017, 2017, 2017, 2017, 2016, 2016, 2016, 2017, 2016, 2017, 2016,
       2016, 2016, 2017, 2016, 2017, 2016, 2016, 2016, 2016, 2017, 2017,
       2016, 2016, 2016, 2017, 2016, 2016, 2017, 2017, 2017, 2017, 2017,
       2017, 2016, 2017, 2017, 2016, 2017, 2017, 2016, 2017, 2016, 2016,
       2016, 2017, 2017, 2016, 2017, 2017, 2016, 2017, 2016, 2017, 2017,
       2017, 2017, 2016, 2017, 2016, 2017, 2016, 2016, 2016, 2016, 2017,
       2016, 2016, 2017, 2016, 2016, 2016, 2017, 2017, 2016, 2017, 2017,
       2016, 2016, 2017, 2016, 2016, 2017, 2017, 2016, 2017, 2016, 2016,
       2017, 2016, 2016, 2016, 2017, 2017, 2016, 2017, 2016, 2017, 2016,
       2017])

In [177]:
# Creating Second variable (job)

#Job=np.random.randint(0, 7, 100)# 0= min ,7 is max and size=100
#Job
# creating a number of  jobtypes 
Jobtypes=['Doctors', 'IT Engineer','Scientist','researchYouth','Administrator']
Job=np.random.choice(Jobtypes,100) # size is 100
Job

array(['researchYouth', 'Administrator', 'Doctors', 'Scientist',
       'Scientist', 'Administrator', 'IT Engineer', 'Scientist',
       'Doctors', 'IT Engineer', 'IT Engineer', 'IT Engineer',
       'Scientist', 'IT Engineer', 'Doctors', 'Scientist', 'Scientist',
       'Doctors', 'Administrator', 'Doctors', 'Scientist', 'Doctors',
       'Administrator', 'Scientist', 'Administrator', 'IT Engineer',
       'Doctors', 'Administrator', 'Scientist', 'IT Engineer',
       'IT Engineer', 'Administrator', 'IT Engineer', 'Administrator',
       'Doctors', 'Scientist', 'IT Engineer', 'Administrator',
       'IT Engineer', 'Administrator', 'Doctors', 'Scientist', 'Doctors',
       'researchYouth', 'IT Engineer', 'researchYouth', 'Scientist',
       'researchYouth', 'Administrator', 'Scientist', 'Administrator',
       'researchYouth', 'Administrator', 'Doctors', 'researchYouth',
       'researchYouth', 'Scientist', 'Scientist', 'Doctors', 'Scientist',
       'researchYouth', 'Doctors', 'IT Eng

In [178]:
# Creating Third variable (Age)
Age= np.random.randint(18,51,100)#min age 18 max age 50  and size is 100
Age


array([24, 25, 37, 43, 20, 39, 21, 34, 39, 35, 49, 26, 43, 38, 18, 44, 19,
       42, 26, 36, 32, 47, 18, 23, 18, 20, 19, 24, 22, 21, 21, 43, 23, 43,
       31, 41, 44, 18, 35, 45, 40, 50, 35, 37, 21, 38, 38, 38, 38, 24, 48,
       47, 24, 19, 47, 23, 27, 30, 22, 20, 49, 29, 18, 47, 22, 24, 47, 36,
       23, 21, 20, 40, 28, 38, 18, 18, 47, 46, 19, 36, 49, 30, 18, 29, 42,
       27, 34, 37, 44, 37, 19, 32, 26, 37, 39, 34, 32, 45, 18, 42])

In [179]:
# Creating Fourth variable (Gender)

#Generate a uniform random sample from Gender of size 100 with replacement:
Gender = ['Male', 'Female']
Gender = np.random.choice(Gender,100) # size is 100
len(Gender)

100

In [189]:
# Creating Fifth variable (Salary)
# Random hours person work in ireland 6 to 20 hours
hours=np.random.randint(6,12,100)
# Random money paid min 10 euro to 20 euro 
money=np.random.randint(10,20,100)
Salary=hours*money
Salary



array([176, 170, 143,  98, 120, 170,  90,  72, 120, 105, 144,  78, 144,
       108, 153, 144,  70, 126, 117, 136, 143, 160, 104, 190,  84, 135,
        90, 198, 144, 105, 121, 128, 108, 105,  84,  66, 170,  66,  66,
       190, 119, 110, 120, 108, 135,  80, 171, 114, 135,  66, 143,  70,
       117, 180, 128, 110, 105, 128, 114,  99, 121,  96,  99, 121, 108,
        70,  77, 198,  60,  84, 119, 209,  88,  99,  77,  84, 112, 154,
        90, 128, 171, 102, 162, 110,  66, 112, 119, 120, 187, 160, 135,
        96, 187, 135,  90,  90,  91, 209, 133,  77])

### Synthesise/simulate a data set

***Adding  all five variable in data frame ***

In [190]:
# using pandas lib to create data frame
import pandas as pd
Df= pd.DataFrame({"Year":Year,"Job":Job,"Age":Age,"Gender":Gender,"Daily Income":Salary})

In [191]:
Df

Age  Daily Income  Gender            Job  Year
0    24           176  Female  researchYouth  2017
1    25           170    Male  Administrator  2017
2    37           143    Male        Doctors  2017
3    43            98  Female      Scientist  2017
4    20           120  Female      Scientist  2016
5    39           170  Female  Administrator  2016
6    21            90  Female    IT Engineer  2016
7    34            72  Female      Scientist  2017
8    39           120  Female        Doctors  2016
9    35           105    Male    IT Engineer  2017
10   49           144  Female    IT Engineer  2016
11   26            78  Female    IT Engineer  2016
12   43           144    Male      Scientist  2016
13   38           108    Male    IT Engineer  2017
14   18           153  Female        Doctors  2016
15   44           144    Male      Scientist  2017
16   19            70  Female      Scientist  2016
17   42           126  Female        Doctors  2016
18   26           117    Male  Administrator  2016
19   36           136    Male        Doctors  2016
20   32           143    Male      Scientist  2017
21   47           160  Female        Doctors  2017
22   18           104    Male  Administrator  2016
23   23           190  Female      Scientist  2016
24   18            84    Male  Administrator  2016
25   20           135    Male    IT Engineer  2017
26   19            90    Male        Doctors  2016
27   24           198    Male  Administrator  2016
28   22           144    Male      Scientist  2017
29   21           105    Male    IT Engineer  2017
..  ...           ...     ...            ...   ...
70   20           119  Female  researchYouth  2016
71   40           209    Male      Scientist  2016
72   28            88    Male    IT Engineer  2017
73   38            99    Male      Scientist  2017
74   18            77  Female        Doctors  2016
75   18            84    Male  researchYouth  2017
76   47           112    Male    IT Engineer  2017
77   46           154    Male      Scientist  2016
78   19            90  Female        Doctors  2016
79   36           128    Male  researchYouth  2017
80   49           171    Male  Administrator  2016
81   30           102    Male      Scientist  2016
82   18           162    Male        Doctors  2017
83   29           110  Female      Scientist  2017
84   42            66  Female  Administrator  2016
85   27           112    Male  researchYouth  2017
86   34           119    Male  Administrator  2016
87   37           120    Male  researchYouth  2016
88   44           187  Female      Scientist  2017
89   37           160    Male  researchYouth  2016
90   19           135    Male      Scientist  2016
91   32            96    Male    IT Engineer  2016
92   26           187    Male        Doctors  2017
93   37           135    Male        Doctors  2017
94   39            90    Male      Scientist  2016
95   34            90    Male      Scientist  2017
96   32            91    Male    IT Engineer  2016
97   45           209    Male    IT Engineer  2017
98   18           133    Male      Scientist  2016
99   42            77    Male  Administrator  2017

[100 rows x 5 columns]

 Checking Number of count for JOB

In [192]:
Df['Job'].value_counts()

Scientist        28
Doctors          21
IT Engineer      20
Administrator    17
researchYouth    14
Name: Job, dtype: int64

Checking Number of count for Male and Female

In [193]:
Df['Gender'].value_counts()

Male      59
Female    41
Name: Gender, dtype: int64

In [194]:
# While describing data set Gender and Job were not appering because its in string form.
#Number each group from 0 to the number of groups - 1.

In [195]:
Df['Gender'] = Df.groupby('Gender').ngroup()
Df['Daily Income'] = Df.groupby('Daily Income').ngroup()

Generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution

In [196]:
Df.describe()

Age  Daily Income      Gender         Year
count  100.000000    100.000000  100.000000   100.000000
mean    32.090000     20.640000    0.590000  2016.490000
std     10.207044     12.250351    0.494311     0.502418
min     18.000000      0.000000    0.000000  2016.000000
25%     22.000000      9.750000    0.000000  2016.000000
50%     33.000000     21.000000    1.000000  2016.000000
75%     40.250000     30.000000    1.000000  2017.000000
max     50.000000     43.000000    1.000000  2017.000000

In [197]:


from faker import Faker
import random
import numpy as np
import pandas as pd
fake = Faker()
fake.random.getstate()
fake.address()
fake.country()
fake.job()
fake.name()
fake.year()
#for i in range(10):
  #j=[fake.name()]
  #(j)
  #print(fake.address())
 # print(fake.country())
  #print(fake.job())
  #print(fake.random.getstate())
  #tt= pd.DataFrame(i)
#t=fake.date_time_between_dates(datetime_start=None, datetime_end=None)
#t



'2003'

In [122]:
df=[fake.name()for i in range (10)]
df1=[fake.country()for i in range (10)]
df2=[fake.year()for i in range (10)]
df3=[fake.job()for i in range (10)]
#tt= pd.DataFrame(np.random.randn(len(NAME)),index=NAME,columns=["FULLNAME"])
#tt= pd.DataFrame([j])
#tt= pd.DataFrame(df,df1,columns=["FULLNAME","FULLNAME1"])


#print(type(df))
df3

['Engineer, energy',
 'Engineer, materials',
 'Rural practice surveyor',
 'Higher education careers adviser',
 'Archivist',
 'Engineering geologist',
 'Forensic scientist',
 'Multimedia programmer',
 'Food technologist',
 'Furniture conservator/restorer']

In [24]:
tt= pd.DataFrame({"job":df3,"Year":df2,"NAMES":df,"COUNTRY":df1})

In [25]:
tt

COUNTRY              NAMES  Year  \
0     Micronesia      Sergio Taylor  1991   
1          India       Victor Lopez  1998   
2        Bolivia      Tiffany Giles  1973   
3           Guam      Diana Goodwin  2003   
4         Turkey        Amber Potts  2014   
5  Faroe Islands         Alexa Yang  1991   
6         Panama     Joshua Hopkins  1970   
7         Guyana        Bryan Black  1997   
8       Barbados  Stephen Smith Jr.  2007   
9       Thailand       Colleen Hays  1998   

                                        job  
0                           Energy engineer  
1                        Facilities manager  
2                               Comptroller  
3  Conservation officer, historic buildings  
4                             Warden/ranger  
5                               Interpreter  
6                Surveyor, building control  
7                       Art gallery manager  
8       Scientist, research (life sciences)  
9                  Customer service manager

In [26]:
ss=tt.sample(3)

In [27]:
ss

COUNTRY           NAMES  Year                         job
7    Guyana     Bryan Black  1997         Art gallery manager
9  Thailand    Colleen Hays  1998    Customer service manager
6    Panama  Joshua Hopkins  1970  Surveyor, building control

### References

https://stackoverflow.com/questions/22639587/random-seed-what-does-it-do

https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html
https://docs.python.org/3/library/statistics.html